---
title: "Data Cleaning"
author: "Ryan Vosbigian & Emma Barton"
date: "5/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

```{r load packages}
library(tidyverse)
```

```{r set pathway}

## Local Pathways - copy/paste your local pathway to the github repository

# Emma
pathway = "/Users/emmabarton/Desktop/spring_2020/STAT434/project/"

# Ryan
#pathway = "~/GitHub/"

```

## Old Code

Old Code to match species
```{r format species name}

# fulldata_df=NULL
# redlist_df$MSW05_Binomial = redlist_df$scientificName
# amniote_df$MSW05_Binomial = paste(amniote_df$genus,amniote_df$species,sep = " ")
# pantheria93_df$MSW05_Binomial = as.character(pantheria93_df$MSW05_Binomial)
# 
# redlist_df$MSW05_Binomial = as.character(gsub("^([^\\s]*\\s[^\\s]*)\\s.*$", "\\1",redlist_df$scientificName)) 
# #https://stackoverflow.com/questions/7449564/regex-return-all-before-the-second-occurrence
# #returns everything before the second space, so that we get the binomial
# redlist_df$MSW05_Binomial[40:50]
# 
# fulldata_df = left_join(x = redlist_df,amniote_df,by="MSW05_Binomial")
# 
# fulldata_df = left_join(x = fulldata_df,pantheria93_df,by="MSW05_Binomial")
# 
# write.csv(fulldata_df,"fulldataset2.csv")

```

```{r check nas}

# fulldata_df = read.csv("fulldataset.csv",header = TRUE)
# 
# 
# # for (i in 1:ncol(fulldata_df)) {
# #   fulldata_df[,i][fulldata_df[,i]== "-999" | fulldata_df[,i]=="NA"] = NA
# # }
# 
# 
# for (i in 1:ncol(fulldata_df)) {
#   print(colnames(fulldata_df)[i])
#   print(table(is.na(fulldata_df[,i])))
# }
# 
# 

```

## Loading Datasets

```{r raw data}

redlist_df = read.csv(paste0(pathway, "STAT-434---not-the-dodo-/simple_summary_IUCN_birds_mammals.csv"))

elton_mammal_df = read.csv(paste0(pathway, "STAT-434---not-the-dodo-/EltonTraits/MamFuncDat.txt"),sep = "\t")

elton_bird_df = read.csv(paste0(pathway, "STAT-434---not-the-dodo-/EltonTraits/BirdFuncDat.txt"),sep = "\t")

```

```{r change raw data types}

redlist_df$scientificName = as.character(redlist_df$scientificName)
elton_mammal_df$scientificName = as.character(elton_mammal_df$Scientific)
elton_bird_df$scientificName = as.character(elton_bird_df$Scientific)

```

```{r join elton and redlist}

# Filter mammals and birds from redlist species
redlist_mammals_df = redlist_df[redlist_df$className=="MAMMALIA",]
redlist_birds_df = redlist_df[redlist_df$className=="AVES",]

# Join Elton traits and redlist species for mammals
mammal_df = left_join(x = elton_mammal_df, y = redlist_mammals_df, 
                      by="scientificName")

# Join Elton traits and redlist species for birds
bird_df = left_join(x = elton_bird_df, y = redlist_birds_df,  
                    by="scientificName")

# Write data
write.csv(mammal_df, "uncleaned_mammal_df.csv")
write.csv(bird_df, "uncleaned_bird_df.csv")

```

```{r uncleaned data}

mammal_df = read.csv("uncleaned_mammal_df.csv")
bird_df = read.csv("uncleaned_bird_df.csv")

```

## Data Cleaning

```{r}

dim(mammal_df)
dim(bird_df)

```

```{r missing redlist species}

table(is.na(mammal_df$Diet.Vect))
nrow(mammal_df)
nrow(elton_mammal_df)
nrow(redlist_mammals_df)

# Check redlist mammals that do not have Elton traits
redlist_mammals_df %>% 
  filter(!(scientificName %in% elton_mammal_df$scientificName)) %>% 
  nrow()

# Check redlist birds that do not have Elton traits
redlist_birds_df %>% 
  filter(!(scientificName %in% elton_bird_df$scientificName)) %>% 
  nrow()

```

```{r select columns}

# Removed unnecessary or mostly empty columns
mammal_df = mammal_df %>% 
  select(-X, -MSW3_ID, -infraType, -infraName, -infraAuthority, 
         -redlistCriteria, -criteriaVersion)

bird_df = bird_df %>% 
  select(-X, -infraType, -infraName, -infraAuthority, 
         -redlistCriteria, -criteriaVersion)

```

```{r missing redlist status}

mammal_df %>% 
  filter(is.na(redlistCategory)) %>% 
  nrow()

bird_df %>% 
  filter(is.na(redlistCategory)) %>% 
  nrow()

```

```{r filter out missing redlist status}

# Create prediction/test datasets 
mammal_pred_df = mammal_df %>% 
  filter(is.na(redlistCategory))

bird_pred_df = bird_df %>% 
  filter(is.na(redlistCategory))

# Filter out rows with missing redlist category to make training dataset
mammal_df = mammal_df %>% 
  filter(!is.na(redlistCategory))

bird_df = bird_df %>% 
  filter(!is.na(redlistCategory))

```

```{r write cleaned data}

write.csv(mammal_df, "cleaned_mammal_df.csv")
write.csv(bird_df, "cleaned_bird_df.csv")

write.csv(mammal_pred_df, "mammal_pred_df.csv")
write.csv(bird_pred_df, "bird_pred_df.csv")

```

